    version: '2'
    services:
      dnsmasq:
        build: dnsmasq
        image: dnsmasq
        ports:
         - "53:53"
        volumes:
         - /forge/myforge/dnsmasq/dnsmasq.hosts:/dnsmasq.hosts
