version: '2'

services:
  dns:
    restart: always
    build: 
      context: dnsmasq
    image: dnsmasq:latest
    hostname: dnsmasq
    container_name: dnsmasq
    ports:
      - "53:5353/udp"
    volumes:
      - /app/myforge/dnsmasq/data/dnsmasq.conf:/etc/dnsmasq.conf
      - /app/myforge/dnsmasq/data/dnsmasq_static_hosts.conf:/etc/dnsmasq_static_hosts.conf
    networks:
      - forge

  nginx:
    restart: always
    build: 
      context: nginx
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /app/myforge/nginx/nginx.conf:/etc/nginx.conf
        - /app/myforge/nginx/conf.d:/etc/nginx/conf.d
    links:
      - gitlab
#      - gogs
#      - nexus
      - jenkins
    networks:
      - forge

  nexus:
#    restart: always
    image: sonatype/nexus3:latest
    hostname: nexus
    container_name: nexus
    ports:
        - "8081:8081"
        - "5000:5000"
    volumes:
        - /app/myforge/nexus/data:/nexus-data
    networks:
      - forge

  postgres:
#    restart: always
    image: postgres
    hostname: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - /app/myforge/postgresql/data:/var/lib/postgresql/data
    networks:
      - forge

  gogs:
#    restart: always
    image: gogs/gogs
    hostname: gogs
    container_name: gogs
    ports:
        - "10022:22"
        - "10080:3000"
    volumes:
        - /app/myforge/gogs/data:/data
    depends_on:
      - postgres
    networks:
      - forge

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - "8022:22"
      - "8080:80"
    volumes:
      - /app/myforge/gitlab/config:/etc/gitlab
      - /app/myforge/gitlab/data:/var/opt/gitlab
      - /app/myforge/gitlab/logs:/var/log/gitlab
      - /app/myforge/gitlab/lfs-objects:/mnt/storage/lfs-objects
    container_name: gitlab
    hostname: gitlab.quangshiba.net
    environment:
      - GITLAB_OMNIBUS_CONFIG="gitlab_rails['lfs_enabled'] = true; nginx['client_max_body_size'] = '2500m';"
      - RAILS_ENV="production"
    networks:
      - forge

  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: runner
    extra_hosts:
      - git.auxylium.toulouse.it.atos.net:192.168.243.88
    volumes:
      - /app/myforge/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /home/quang/.docker/config.json:/root/.docker/config.json
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8

  jenkins:
    image: jenkins
    restart: always
    hostname: jenkins
    container_name: jenkins
    ports:
        - "49001:8080"
    volumes:
        - /app/myforge/jenkins/data:/var/jenkins_home:z
        - /usr/bin/docker:/usr/bin/docker
        - /usr/local/bin/docker-compose:/usr/bin/docker-compose
    networks:
      - forge

  jenkinsslave:
    build: jenkins-slave
    ports:
        - "0.0.0.0:222:22"
networks:
  forge:
    driver: bridge

