version: '2'

services:
  dns:
    build: 
      context: dnsmasq
    image: dnsmasq:latest
    hostname: dnsmasq
    container_name: dnsmasq
    ports:
      - "53:5353/udp"
    volumes:
      - /mnt/sda1/myforge/dnsmasq/data/dnsmasq.conf:/etc/dnsmasq.conf
      - /mnt/sda1/myforge/dnsmasq/data/dnsmasq_static_hosts.conf:/etc/dnsmasq_static_hosts.conf
    restart: always


  nexus:
    image: sonatype/nexus3:latest
    hostname: nexus
    container_name: nexus
    ports:
        - "8081:8081"
        - "5000:5000"
    volumes:
        - /mnt/sda1/myforge/nexus/data:/nexus-data
    restart: always

  postgres:
    restart: always
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
    ports:
      - '5432:5432'
    volumes:
      - /mnt/sda1/myforge/postgresql/data:/var/lib/postgresql/data

  gogs:
    image: gogs/gogs
    hostname: gogs
    container_name: gogs
    ports:
        - "10022:22"
        - "10080:3000"
    volumes:
        - /mnt/sda1/myforge/gogs/data:/data
    restart: always
    depends_on:
      - postgres
